"""add usage tracking, response cache, kb articles, agent budget

Revision ID: 32f37eeb9f1f
Revises: 03f641236737
Create Date: 2026-07-02 20:09:27.477180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32f37eeb9f1f'
down_revision: Union[str, Sequence[str], None] = '03f641236737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('tema', sa.String(length=255), nullable=False),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('respuesta', sa.Text(), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('response_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('hash_prompt', sa.String(length=64), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_cache_hash_prompt'), 'response_cache', ['hash_prompt'], unique=False)
    op.create_table('usage_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('tool_calls', sa.Integer(), nullable=False),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agents', sa.Column('agent_code', sa.String(length=50), nullable=True))
    op.add_column('agents', sa.Column('daily_budget_usd', sa.Float(), nullable=True))
    op.create_unique_constraint('uq_agents_agent_code', 'agents', ['agent_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_agents_agent_code', 'agents', type_='unique')
    op.drop_column('agents', 'daily_budget_usd')
    op.drop_column('agents', 'agent_code')
    op.drop_table('usage_log')
    op.drop_index(op.f('ix_response_cache_hash_prompt'), table_name='response_cache')
    op.drop_table('response_cache')
    op.drop_table('kb_articles')
    # ### end Alembic commands ###
